Fix/3.9 to 3.10
WordPress/openverse-catalog pull request #656
Opened 2022-08-11 13:52 UTC by sarayourfriend

## Fixes

Fixes #607 by @AetherUnbound 
Fixes #655 by @sarayourfriend 

## Description

Centralises the Python version declaration in a single place so that it can't drift again. Also sets it to 3.10 as the issue required.

I also went ahead and removed the template files as I don't think they're being used anymore. I can undo this bit if necessary.

## Testing Instructions

Checkout the branch and run `just recreate` and confirm that it uses 3.10 for everything, the base image and the constraints file. Confirm that everything installs correctly and runs well (CI will confirm this as well).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-08-11 14:49 UTC, obulat requested changes
Oops, I just noticed that the tests for the templates also need to be deleted to pass the CI.

2022-08-11 15:37 UTC, obulat approved these changes
LGTM!

2022-08-11 15:41 UTC, dhruvkb approved these changes
👏 This PR has some very innovative approaches to reuse the value defined in one file in so many different places.

We should do the same for `WordPress/openverse-api` as well.

2022-08-11 16:24 UTC, sarayourfriend commented
Waiting on @AetherUnbound or @stacimc to review this and confirm the approach before merging.

2022-08-15 21:32 UTC, sarayourfriend commented on justfile
> +# Check the installed Python version matchese the required Python version and fail if not
```suggestion
# Check the installed Python version matches the required Python version and fail if not
```

2022-08-16 21:02 UTC, AetherUnbound approved these changes
I love this approach! Once I rebased this on main and fixed the conflicts, all of the tests passed. I'm happy to push that rebase if you'd like.

I am getting an error when I try to run `just run python -v` 🤔 never seen anything like it, I'll try to look into it a bit more. The way it's behaving for me, it would seem to be a permissions issue that'd persist for v3.9 too, or any recent iteration of our docker image.

<details><summary>Output of `just run python -v`</summary>

```
####################################################################################################################################################################################################################
                                                                                                RUNNING "python -v"
####################################################################################################################################################################################################################
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# code object from /usr/local/lib/python3.10/encodings/__init__.py
# could not create '/usr/local/lib/python3.10/encodings/__pycache__/__init__.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/codecs.py
# could not create '/usr/local/lib/python3.10/__pycache__/codecs.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d002d150>
# code object from /usr/local/lib/python3.10/encodings/aliases.py
# could not create '/usr/local/lib/python3.10/encodings/__pycache__/aliases.cpython-310.pyc': PermissionError(13, 'Permission denied')
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d0067c40>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d01bf6a0>
# code object from /usr/local/lib/python3.10/encodings/utf_8.py
# could not create '/usr/local/lib/python3.10/encodings/__pycache__/utf_8.cpython-310.pyc': PermissionError(13, 'Permission denied')
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d006c190>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# code object from /usr/local/lib/python3.10/io.py
# could not create '/usr/local/lib/python3.10/__pycache__/io.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/abc.py
# could not create '/usr/local/lib/python3.10/__pycache__/abc.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d006e0b0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d006c4c0>
# code object from /usr/local/lib/python3.10/site.py
# could not create '/usr/local/lib/python3.10/__pycache__/site.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/os.py
# could not create '/usr/local/lib/python3.10/__pycache__/os.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/stat.py
# could not create '/usr/local/lib/python3.10/__pycache__/stat.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d0070220>
# code object from /usr/local/lib/python3.10/_collections_abc.py
# could not create '/usr/local/lib/python3.10/__pycache__/_collections_abc.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d0035f30>
# code object from /usr/local/lib/python3.10/posixpath.py
# could not create '/usr/local/lib/python3.10/__pycache__/posixpath.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/genericpath.py
# could not create '/usr/local/lib/python3.10/__pycache__/genericpath.cpython-310.pyc': PermissionError(13, 'Permission denied')
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d007a290>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d00c4700>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d00962f0>
# code object from /usr/local/lib/python3.10/_sitebuiltins.py
# could not create '/usr/local/lib/python3.10/__pycache__/_sitebuiltins.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d00d9540>
Processing user site-packages
Adding directory: '/usr/local/airflow/.local/lib/python3.10/site-packages'
Processing global site-packages
Adding directory: '/usr/local/lib/python3.10/site-packages'
Processing .pth file: '/usr/local/lib/python3.10/site-packages/distutils-precedence.pth'
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7d0035b10>
Python 3.10.1 (main, Dec 21 2021, 09:17:12) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/usr/local/lib/python3.10/lib-dynload/readline.cpython-310-x86_64-linux-gnu.so'
# extension module 'readline' executed from '/usr/local/lib/python3.10/lib-dynload/readline.cpython-310-x86_64-linux-gnu.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7fb7d007b6d0>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# code object from /usr/local/lib/python3.10/rlcompleter.py
# could not create '/usr/local/lib/python3.10/__pycache__/rlcompleter.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/inspect.py
# could not create '/usr/local/lib/python3.10/__pycache__/inspect.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/ast.py
# could not create '/usr/local/lib/python3.10/__pycache__/ast.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_ast' # <class '_frozen_importlib.BuiltinImporter'>
# code object from /usr/local/lib/python3.10/contextlib.py
# could not create '/usr/local/lib/python3.10/__pycache__/contextlib.cpython-310.pyc': PermissionError(13, 'Permission denied')
# code object from /usr/local/lib/python3.10/collections/__init__.py
# could not create '/usr/local/lib/python3.10/collections/__pycache__/__init__.cpython-310.pyc': PermissionError(13, 'Permission denied')
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# code object from /usr/local/lib/python3.10/keyword.py
# could not create '/usr/local/lib/python3.10/__pycache__/keyword.cpython-310.pyc': PermissionError(13, 'Permission denied')
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb7cff28250>
# code object from /usr/local/lib/python3.10/operator.py
# could not create '/usr/local/lib/python3.10/__pycache__/operator.cpython-310.pyc': PermissionError(13, 'Permission denied')
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator'  [...]

2022-08-16 21:45 UTC, merged