Update .pre-commit-config.yaml
WordPress/openverse-catalog pull request #718
Opened 2022-09-08 14:10 UTC by MustkimKhatik

adding shellcheck to openverse-catalog repo

2022-09-08 14:14 UTC, dhruvkb requested changes

2022-09-08 14:17 UTC, MustkimKhatik commented
Yeah I did that change

2022-09-08 14:19 UTC, dhruvkb commented
@MustkimKhatik ShellCheck is now running as expected, and flagging [a number of warnings and errors](https://github.com/WordPress/openverse-catalog/runs/8251392427?check_suite_focus=true#step:7:90). Could you take a look at the ShellCheck output and implement the changes it recommends?

2022-09-08 14:36 UTC, MustkimKhatik commented
Yeah, I'll do them!

2022-09-15 20:01 UTC, krysal commented
@MustkimKhatik are you still able to take on the the ShellCheck recommendations?

2022-09-16 04:45 UTC, MustkimKhatik commented
Yep, I'm on them.

2022-09-16 06:05 UTC, MustkimKhatik commented
Hey @krysal, [current in dag-sync.sh](https://github.com/MustkimKhatik/openverse-catalog/blob/patch-1/dag-sync.sh#L46), it was unused variable and to resolve it I used ```echo```. there was a option to ```export``` too. I will appreciate if you tell me what will be more appropriate here to use?

2022-09-18 11:05 UTC, dhruvkb approved these changes
Apart from one change, this looks good to me. Thanks @MustkimKhatik!

2022-09-18 11:05 UTC, dhruvkb commented on dag-sync.sh
> +echo "$current"
Since it's an unused variable, we could just remove it altogether.

2022-09-18 11:10 UTC, MustkimKhatik commented
> Apart from one change, this looks good to me. Thanks @MustkimKhatik!

Sure, I'll do that change.

2022-09-20 15:16 UTC, obulat approved these changes
This is such a useful addition, it feels like magic! Thank you for your contribution, @MustkimKhatik, and welcome to Openverse!

2022-09-20 15:20 UTC, MustkimKhatik commented
> This is such a useful addition, it feels like magic! Thank you for your contribution, @MustkimKhatik, and welcome to Openverse!

You're welcome and that's my pleasure to work with openverse!

2022-09-20 17:38 UTC, AetherUnbound approved these changes
Thank you for the addition, the changes look great!

2022-09-20 17:39 UTC, merged