Refactor Jamendo to use the ProviderDataIngester
WordPress/openverse-catalog pull request #741
Opened 2022-09-24 00:34 UTC by stacimc

## Fixes

Fixes #587 by @stacimc 

## Description

Refactors Jamendo to use the ProviderDataIngester base class.

## Testing Instructions

* Run the Jamendo provider script locally
* Try setting an `ingestion_limit`, maybe try setting some of the dagrun conf options like `initial_query_params`
* Inspect the tsv
* `just test`

## TODO
Finish pr description, final review before undrafting

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2022-10-06 23:14 UTC, AetherUnbound requested changes
This looks great and works fine locally! I think the log settings need to be changed, but after that this is good to go 💯

2022-10-06 23:14 UTC, AetherUnbound commented on openverse_catalog/dags/providers/provider_api_scripts/jamendo.py
> +        logger.info(license_url)
Should this and other `logger` calls be at `logger.debug`? It seems like this is at least 5 log lines per record which could be a lot.

2022-10-06 23:14 UTC, AetherUnbound commented on tests/dags/providers/provider_api_scripts/test_jamendo.py
> +    assert jamendo.get_batch_data({}) is None
We could group these two tests in a parametrization!

2022-10-06 23:14 UTC, AetherUnbound commented on tests/dags/providers/provider_api_scripts/test_jamendo.py
> +    assert jamendo.get_record_data(audio_data) is None
These 3 tests could also potentially be parametrized.

2022-10-07 19:26 UTC, AetherUnbound approved these changes
Fantastic!

2022-10-10 14:55 UTC, krysal approved these changes
Looks great!

2022-10-10 23:46 UTC, merged